# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator-default
  labels:
    heritage: default
---
apiVersion: v1
kind: Secret
metadata:
  name: default-validating-certs
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDRENDQXZDZ0F3SUJBZ0lVUzNJaHI5VXlKYy8vNGN2dStKZXExUVZ0NXRNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FERStNRHdHQTFVRUF4TTFVMmhsYkd3dGIzQmxjbUYwYjNJZ1pYaGhiWEJzWlNBeU1EUXRkbUZzYVdSaApkR2x1WnkxM1pXSm9iMjlySUZKdmIzUWdRMEV3SGhjTk1qUXhNVEV4TVRrMU5EQXdXaGNOTWpVeE1URXhNVGsxCk5EQXdXakF4TVM4d0xRWURWUVFERXlaa1pXWmhkV3gwTFhaaGJHbGtZWFJwYm1jdGMyVnlkbWxqWlM1a1pXWmgKZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMOVAwYjdKcDJGdApGTEdzR2ZUWGpvOUFjQUFydHhLRU96cVhuTFJJOVdjZDdNOEdsMDRNNjR2MjFGeisyYmVXMXJQaWtUcW5JTEtGCmNlUWxXSzAwcldPS3E3V3luakl3V01NVDZzYlR2aFA4TVVvazB3OUsvK096WStVUzhHMXJFeGw5aGdqUlZpc3kKcW5waXNNMktSK1ZJN3pCeFlyNlFaVGFkUW5WS2ZPc3NjK0QyWkNyRFpFVWQydDIxdEFmOGFiVGhBaVZsUUVJdwp0WFgwY3huUWU0Yi9FdmJoQnFVR01MZEJ5QnVjTlRCUmluVjhUaG5tNFRrb0lGbExsVVZCWlYwSHJVdEk2TkpxCjZINDJnbjg1TlRuWWh2ZWxIZStGYitZcFdITzR3Y2t0RXMrUWJ0V2h4cS9lM3E4RU5DcDVpZVpFQXRVcGFVU1MKeWRhRG1Ub1BsenNDQXdFQUFhT0NBUWN3Z2dFRE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBSwpCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGFXYm5GT3N0Ym1EVkpLU1lXCnNCaEJSdnlCZWpBZkJnTlZIU01FR0RBV2dCUVUxQXQ3RThMQ1lGSGRheWNJZ3lGTmtKTmthVENCalFZRFZSMFIKQklHRk1JR0NnaUprWldaaGRXeDBMWFpoYkdsa1lYUnBibWN0YzJWeWRtbGpaUzVrWldaaGRXeDBnaVprWldaaApkV3gwTFhaaGJHbGtZWFJwYm1jdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMlk0STBaR1ZtWVhWc2RDMTJZV3hwClpHRjBhVzVuTFhObGNuWnBZMlV1WkdWbVlYVnNkQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUcKOXcwQkFRc0ZBQU9DQVFFQWlqN0NjaW1NaWJUQkQvNlppK1dFcGVpbUhaNm1ZUWJYdkdKTlFZWWxxYStyWlhUbApmUWw4ekg1QmdVQlN1S0MvQmxyZkgrSjZxRnJtYUFlNHpvRC80LzhVLzBIZ3I0VDdpNjRldlI0NkhhOGU1bERFCkhjMGR3UUwrRnRNdXBkQ21sTXFRZnhPRnlRNkxGZktrbkM0VklLYnV0bnhSdHlJU0RaOUJqS01JeFAvUjhqY2YKU2pjdm15dEU4aTlIK0FGWWhOTVR3aEgxL0JpRFJJUFZHbVNwU09wNDRSYzhlTXdaWU02NWU2U1kzSkE3UUE3TQptTWh1MUZSbnBmemFpVFNEVTJMcEtiYlNlcmhsYUZhTkRMUGVISmlXbGpLVU1NTHd6ZGFVb0c0M1BkT05SUnVlCk9PbDViZnBFTXdSWUgxSnRoMm9CY3FLbURta1pNcWdWUUFBU2dnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdjAvUnZzbW5ZVzBVc2F3WjlOZU9qMEJ3QUN1M0VvUTdPcGVjdEVqMVp4M3N6d2FYClRnenJpL2JVWFA3WnQ1YldzK0tST3FjZ3NvVng1Q1ZZclRTdFk0cXJ0YktlTWpCWXd4UHF4dE8rRS93eFNpVFQKRDByLzQ3Tmo1Ukx3YldzVEdYMkdDTkZXS3pLcWVtS3d6WXBINVVqdk1IRml2cEJsTnAxQ2RVcDg2eXh6NFBaawpLc05rUlIzYTNiVzBCL3hwdE9FQ0pXVkFRakMxZGZSekdkQjdodjhTOXVFR3BRWXd0MEhJRzV3MU1GR0tkWHhPCkdlYmhPU2dnV1V1VlJVRmxYUWV0UzBqbzBtcm9mamFDZnprMU9kaUc5NlVkNzRWdjVpbFljN2pCeVMwU3o1QnUKMWFIR3I5N2Vyd1EwS25tSjVrUUMxU2xwUkpMSjFvT1pPZytYT3dJREFRQUJBb0lCQUdyK3pES2srMHpjd2Q4ZwpmcC9WMHJCQmZLSkwwS2ExZDU2c1hvTGg3d1hOMGJ4elZqbmJ0ZnpnZmlMSWthRkE1akZTL0tCT0NsWnRsYVhnClVUa0ZwaGR1M2R2UDJ2UDg0QmV5VXZNQ1IyTkwvNUVWQ1VtYlM0UGd0M1ROWTlQK04zOWhHWTVpN1l0WldjajYKMnlFSlBtNTRuUFY5NUpqcGp3RzljQWJETXh3ZkZqdGJCbEdVQWdqckVBVGxCaUlWWkhjODQxMVQ4M2l1QmpsOAo1aFNzcG1vYXdyekFrcDVyZnVpNDczNG5hRlZHb1NPRC84c3cyNVdKNlZPcm0zTVhibXNsZlp2THFEeXh4dGUzCjIxOEpKc2dZSThab2JRQ1g0NStGRGx5dUtlcWM3RnQwdkZKOVpiMHVKSmM1M2ZaWjBVLzdDYmxoTDBESkszK3MKOFFSV21Ha0NnWUVBK0ZqN1REbjE3OFBBNzh2aGhwb05HWis3Ym1LV3N2dmhWREt3SmR1c0NBV2NCZmdiVHh3YwptSSt0UkNZU2o4R0tQV3ptQmtsT3lpWDBEU0hjelp3eWs5aVNtMUxIbzV5WkswbkV0Mkl5TlZZVUtQUHVINWxqClpydGN5RW9Wak44UTRVTGU4UXZLWHVJQnY0MlJ4OXBnWjA5UUlvMTZOVmJhbnJpQ05oc01TUzBDZ1lFQXhUVHQKWXFmZ1BTbEo2Z0JXNnl5cFp1T3Fxd25kT0hWYWlxMUM4eVBEbkkvQ2QwNzQ1elhsRklLOTdMSm5kRDVnY2dkdApPVlBxNmJqdTdGbms4dEc0MWkzUThlck9nUHpJenlwVGdGaU5TbElybktQV21GdFdUSGtqZW1UZ0x2cXpBaVRIClNNZzNUTXhnZkhmSE9EcUEvdTI1Z21SN1ZzOGFqbFQ5bmlVQVV3Y0NnWUVBMHdhSlFwUmRyb2FnQXlNelY3Uy8KUE83RnpWNW92MTNZY2p0QUFtdFBHdUhwV2drZzYyL3Z2Sk1abjdiYVB0MHVJbFBPZ2JqNUFqeU56RHJoN0xTMQpKWHY1MTVIWG9lY0hJQWxtNW96Q0xTQWZzVXpWSW5Tc1NqY2E5L1k3cWFCQ0w2Y3EyWmd6TmJ6Rno0YjBRT1lHCjFNSklUWlA2TENqSlMrVnNmNTBzSzJFQ2dZQWpYekh4RHlGMmR2QnVDMitMc1RBVloyS1dXU2VYMTl6TW9QVXcKUFVyNXl3TmJlUXZHRlBHbzh5Wnp6VEFuTm9VQUR2cjFYR3IzVHhkengwLzhpY2Q0aXpFK0l4cTFJaUkybm1YcAowSGhQUzF2Tk5jbm8vQUVIcUhiSG5rNWp2czNhNVpQbEp4eGNKeEJyWXVTVjNsQ0M2VXJyNjNBQUN4ZTlUZHRMCndXRkVnd0tCZ1FDMlRTZlpZVGJsc0RPeWhjVXl6a3k3NS9RQnB6dUNWVEtVV1Uxa0dReE15d0hib2xDOGhQdEMKQzZyRzB5d0l0OUVUU1hHS2M2YU1Bcm1HMkEwMHB1aTlWaGdMSnBTOHpUclpiMzd4UEtzbjF6ZmhRWklTSGRNUwpxa2NGMXV4RTJmbkNWclVOZEhvNU05MnpvNkVjMGxlU2N0MnFuRzhROGlLRDY2Yk5HdzZlL3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVRENDQWppZ0F3SUJBZ0lVUkU5c2ViN2ZtMHR2cWw2LzBsUHpUN056bzJZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FERStNRHdHQTFVRUF4TTFVMmhsYkd3dGIzQmxjbUYwYjNJZ1pYaGhiWEJzWlNBeU1EUXRkbUZzYVdSaApkR2x1WnkxM1pXSm9iMjlySUZKdmIzUWdRMEV3SGhjTk1qUXhNVEV4TVRrMU5EQXdXaGNOTWpreE1URXdNVGsxCk5EQXdXakJBTVQ0d1BBWURWUVFERXpWVGFHVnNiQzF2Y0dWeVlYUnZjaUJsZUdGdGNHeGxJREl3TkMxMllXeHAKWkdGMGFXNW5MWGRsWW1odmIyc2dVbTl2ZENCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFLcUptK2ZKU3NGTG5vaGlXaElsSTcyU1Y4Wlh4bGRhamZMb3U4Zll3czFiYldod3pWcjJmVDZFCmgxdnd2aE0wZG5YMHNzUWFvMFptVjJscTBhTzJGd0FIcWg1RUdGS2djZm5WUHYrQjRCZm9tSEZ5cmp3UjlTcnQKaEc3U3hoaDYyMnoraDQ1WExvWjZyaDlwTUkrdFNrK2ZRd0FibHdHQUlyQ01lTVo5YUlia1ArRi9QSlc5OFhjQgphaGE2Uk5qMUI4VnM4dEJZSWxjOEtEOFFrRjBUZGdlRVl0WlFNNG9jbkM4MmFTY0dSVCtNaVFJSFgySzZQTXRyCk5LNDZEY0hwU0UwRGRjZTNKUmNDaE95OHpzME9TNGkwRWFXcW5xMnRIeWgrclhncUlnQ1prOG9uSy84SXRiTXEKbzZWZVdGejk2TDJYbnd0Zk9aVGZuRE90Rm1iMGg0a0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFRwpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQlRVQzNzVHdzSmdVZDFySndpRElVMlFrMlJwCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmJUS0tHd0ZUcDhsL2J5RWN3WUo5a0lZdlR6OWJYNzNhOUg2U3YKb1RielhtNmloaGZnbG5LSXgvUmtKWFdPdFF5bEtkcjJvNTdjaG8xY3FsdjNKU000Q3M1aUp2bnF5OFo2cGlhNQpMaE9IeWJyRGdGZUNCNkNQU2tmWFcwa2ZLU2p5NXRndjRSZzhrejNWRlJackZERU9nUk9QdFozbjJJTGtTZitYCi95UExiWlRCbVIxczA3UUd5Vzc0dDQ3M1hHeVBBWHliTkkvOUFXZG1zS0sxQTNnUmp2S29QZnNTdGZBNXQ3SloKdGxPVVovUzdtRWhpWllxd2pQSHZmZVhvL0dEM3hyMEFlMnVabElTZ0gvNWZXZEJKTnJ3bGRFUGtSeUZLNitoTwpaUlhUMVkzSWFBS2pDdmI4ZEJQNy9WL1hyTVZwRkVyUWRBK25rb0Q2NzBiVS9GaE0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shell-operator-default
  labels:
    heritage: default
rules:
- apiGroups: 
    - "admissionregistration.k8s.io"
  resources: 
    - "validatingwebhookconfigurations"
  verbs: ["*"]
- apiGroups: ["networking.gke.io"]
  resources: ["networks"]
  verbs: ["*"]
- apiGroups: 
    - "vm.cluster.gke.io"
  resources: 
    - "virtualmachines"
  verbs: ["*"]
- apiGroups: 
    - ""
  resources: 
    - "pods"
  verbs: ["get","read","list"]
- apiGroups: 
    - "kubevirt.io"
  resources: 
    - "virtualmachineinstancemigrations"
    - "virtualmachineinstances"
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shell-operator-default
  labels:
    heritage: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shell-operator-default
subjects:
  - kind: ServiceAccount
    name: shell-operator-default
    namespace: default
